version: "3.7"
services:
  notebook:
    image: jupyter/base-notebook
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /share/data
        target: /home/jovyan/work
      - type: bind
        source: /share/pipenv
        target: /home/jovyan/.local
